Refactor the Application configuration startup code
Azure-Samples/iot-edge-opc-plc pull request #101
Opened 2021-12-28 13:09 UTC by mregen

## Purpose

* Refactor the Application configuration startup code, to address issues with cert creation and tbd enhancements of the UA stack.

## Does this introduce a breaking change?
```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code, start the app

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check
Verify that the following are valid
* opc plc startup code works as usual

2022-01-13 11:25 UTC, luiscantero requested changes

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +            Logger.Information($"LDS(-ME) registration intervall set to {LdsRegistrationInterval} ms (0 means no registration)");
typo interval

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +            var application = new ApplicationInstance() {
We use curly braces in the next line for this solution. Please reformat document.

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +                ApplicationType = ApplicationType.Server
Add trailing comma

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +            var application = new ApplicationInstance() {
Cosmetic: Remove ()

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +            Logger.Information($"opcstacktracemask set to: 0x{OpcStackTraceMask:X}");
Is there a more meaningful name for opcstacktracemask that we can log here?

2022-01-13 11:25 UTC, luiscantero commented on src/OpcApplicationConfiguration.cs
> +                Logger.Information($"with a {CertificateFactory.DefaultKeySize} bit key and {CertificateFactory.DefaultHashSize} bit hash.");
This will generate two log lines with two different timestamps. Pls merge the string instead.

2022-02-01 11:53 UTC, mregen commented on src/Program.cs
>  using System.Threading;
wohoo

2022-02-01 12:11 UTC, mregen commented
@luiscantero all resolved

2022-02-01 12:16 UTC, luiscantero approved these changes

2022-02-01 12:45 UTC, merged